FROM golang:alpine
WORKDIR $GOPATH/src/github.com/ageapps/gambercoin
ADD . .
RUN go get ./...
RUN go build -o node_headless ./cmd/node_headless
RUN adduser -S -D -H -h /app appuser
USER appuser
ENV PORT=8080
CMD ["./node_headless"]
